version:              2
jobs:
     build:
          docker:
               - image: circleci/ruby:2.4.3
          steps:
               - checkout
               -run:  bundle exec jekyll build
     test:
          docker:
               - image: circleci/ruby:2.4.3
          steps:
               - checkout
               -run:  bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html --assume-extension
